- repo: https://gitlab.com/pycqa/flake8
  rev: 3.7.7
  hooks:
    - id: flake8
- repo: https://github.com/pre-commit/mirrors-mypy
  rev: v0.780
  hooks:
    - id: mypy
      args: []
      pass_filenames: false
